---
title: "Access & Security"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Access & Security}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The `{markr}` package uses Google Sheets as persistent storage of user IDs and user submissions. This vignette provides some explanation and instructions for setting up your `{learnr}` tutorials so that they can read from and write to the appropriate files in your Google space.

A `{learnr}` tutorial  is a kind of Shiny app. Writing and deploying a tutorial requires Shiny programming practices. Usually this are practically invisible and a tutorial source document looks very much like an ordinary Rmd document. Storing a record of user interactions with the tutorial, however, does involve using programming constructs for what is called "persistent storage." (Background on  several kinds of persistent storage is given [here](https://deanattali.com/blog/shiny-persistent-data-storage/).) 

You can use `{markr}` without any understanding of persistent storage beyond these two steps:

1. Creating the Google sheets i) to hold user IDs and ii) to hold the record of user interaction with the tutorial.
2. Creating the means of login access to the sheets in (1) for the  deployed tutorial  to use.

## Creating Google Sheets

For these instructions I am using a Google account with address `StatPrep.Annie@gmail.com`. You can use your own Google account, but for security reasons you may want to consider setting  up and using another account in order to avoid inadvertently providing access to your personal files on Google Drive.

1. Log in to the Google Drive account you will be using as the persistent storage for  your tutorials.

Within Google Drive, you may want to create a directory to hold the storage. 

2. Create a Google Sheet file with a first row consisting of two names: "id" and "password". Populate additional rows with the user names you will assign to your tutorial users and with a password. Note that passwords will be stored in plain text, so *do not* use passwords that should be kept confidential. (Using a convention for passwords like "banana-tiger" produces passwords that are easy to remember.)

3. As for every file stored on  Google Drive, there will be a unique URL assigned.  For the file used in  this example, the link is <https://docs.google.com/spreadsheets/d/1WvQDD1sQHcc_aZ1eisWkZvhU4a3jEAR2HXt_1REojpM/edit?usp=sharing>.

4. Copy  out  the "key" from the file's URL. You will need this key for each tutorial that you write using `{markr}`. For the URL in (3),  the key  is `"1WvQDD1sQHcc_aZ1eisWkZvhU4a3jEAR2HXt_1REojpM"`.

5. Repeat steps 2 through 4 to create a second Google Sheet to hold the submissions. This sheet will have 10 named columns, as in  the example file  at <https://docs.google.com/spreadsheets/d/14z7FM64GUq8nc6Q4zvJKH5ynEY2lBttiIIqAxmEgojA/edit?usp=sharing>. You will use  the key for this submission file (`"14z7FM...EgojA"`) in  your `{markr}` tutorials.

## Caching your Google Sheets credential

Your `{learnr}/{markr}` tutorial will, when  you run it, need to  access the sheets you've just created. The next section shows how to direct  your tutorial to the right storage by using the keys you created in the previous section.

**Before**  you can do this successfully, you will need to *cache* an authorization "token" to be used.

1. If you haven't already done so, install the `{googlesheets4}` and `{googledrive}` packages.
2. At the R console, give these commands:

```r
options(gargle_oauth_cache = ".secrets")
googledrive::drive_auth()  
# In response, Google will ask for permissions ...  
# give them, then
googlesheets4::sheets_auth(token = drive_token())
```
   
In response to `drive_auth()`  command in the above, your  browser should direct you to log in to Google Sheets. Login to the account you used to store the password and submission files in the previous section. Accept the requests for  permission to  access your account.

At the end of this process (Remember the `sheets_auth()` command from the above!), you should have a directory called `.secrets` in the current working directory.  In the `.secrets` directory there will be a file with a name like

`626f181d0271802a652ecd26ed5dc62e_yourname@gmail.com

3. Give the  R command `getwd()` to remind yourself of where the `.secrets`  directory has just been created.
    
4. Whenever you  write a `{learnr}` tutorial that uses the `{markr}` system,  it will be in whatever directory you set up. We'll call that the tutorial directory. Your job now is to copy the `.secrets` directory (and the file within) into the  tutorial directory. This is straightforward, *except* RStudio doesn't give access to files or directories starting with a period. So you will have to use the terminal to copy the directory. This involves some UNIX commands. 

- `ls  -a` : will  list all files in the current directory.
- `ls -a .secrets`: will tell you whether the directory you  are currently in  has a `.secrets`  directory
- `cd [directory]` : will set the current working directory (in UNIX). Replace `[directory]` with the directory location you found in step (3). 
- `pwd` : will tell you  the current working directory, so that you  can confirm you are where you want to be. 
- `cp .secrets [path to the tutorial directory]` will make a copy of the  `.secrets` directory  (and its contents) in the place you specify.

The  `.secrets`  directory must be called exactly `.secrets`  and  must be  in  the same directory as your tutorial Rmd file.


Note that when you eventually *deploy* your tutorial,  e.g. to `shinyapps.io`, the `.secrets` directory will also be uploaded. You should see `.secrets` listed among the files to be included with the deployment.

But first, you have to set up your tutorial Rmd file to use `markr`.

If you desire to  deploy  apps as  part  of a package, with  the apps to  be  run on  the  user's own system, I *do not yet* have a way to  keep the `.secrets` directory secret. It has to be part of  your app. **Suggestions for how to  accomplish  this would be  appreciated.**

## Writing a tutorial with `{markr}` storage.

You write `{markr}` tutorials in a perfectly ordinary  way. To implement the storage, add a chunk to the file. It seems sensible to make this the first section  in the tutorial so that users will encounter it *before* working the actual exercises and questions in the tutorial. The chunk will look like this:

````
`` `{r login-chunk-name,  echo=FALSE}
library(markr)
# Use your own password and storage keys
password_key <- "1WvQDD1sQHcc_aZ1eisWkZvhU4a3jEAR2HXt_1REojpM"
store_key    <- "14z7FM64GUq8nc6Q4zvJKH5ynEY2lBttiIIqAxmEgojA"
user_ID(key = password_key, store = store_key)
`` `
````

Once you've modified your tutorial to include the login chunk, but **before deploying it**, test it out on your computer. This simply means pressing the "Run Document"  button  in RStudio (or any other way of running a tutorial document).

In  the login section of the document--the section you created!--you will see a text-entry box. Enter a user ID and password in your Google Sheet password file in this format:

    userid::password

Press "Submit login credentials".

[Perhaps someone will help me re-organize this so that the user ID and password go into separate text-entry boxes and  the password  is not  shown  in plain text.]

Now submit answers from the exercises and questions in your tutorial. As you do so, one or more rows will  be added to the submission storage sheet. (You can see this by opening the sheet in a browser in the ordinary way for Google Sheets.)

Notice  that in  the submission store sheet, there  are fields `tutorial-id` and  `tutorial-version`. These will  be filled  in by default  with  the name  of  the  directory in which the tutorial Rmd file lives. It's  highly recommended  that  you set these manually in the YAML  section of your tutorial to  have unique  values as with this  example  copied from  the  `{learnr}` documentation:

    tutorial:
      id: "com.example.tutorials.my-first-tutorial"
      version: 2.1

## Revising your tutorial

In the  ordinary course of events you  may want  to revise your tutorial, adding,  deleting, or changing questions.  Some tips:

1. Leave  the `tutorial_id` as you initially set it (unless you regard the revision  as a "new" tutorial.)
2. Update the version number.
3. Leave chunk names  alone so that submissions from  the revised document will  correspond  to submissions from the previous versions. Of course, if  you add a  new question, you'll need  to  give it a new, unique chunk name. The in-between case--when you revise a question substantially--I leave to your own judgment.  Note that for `{learnr}` *questions*, the stored submission  will contain a `TRUE/FALSE` indicator for whether the answer was correct in the version in  use at the time of submission.

